version: "2"
linters:
  default: none
  enable:
    - bodyclose
    - gocritic
    - govet
    - ineffassign
    - staticcheck
    - testifylint
    - unused
  settings:
    govet:
      disable:
        - fieldalignment
      enable-all: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - bodyclose
        path: .*_test.go
    paths:
      - .tmp
      - vendor
      - third_party$
      - builtin$
      - examples$
      - internal/zeroperl$
formatters:
  enable:
    - goimports
  exclusions:
    generated: lax
    paths:
      - .tmp
      - vendor
      - third_party$
      - builtin$
      - examples$
      - internal/zeroperl$
